# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_User_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.NullBooleanField(verbose_name='first name')),
                ('last_name', models.NullBooleanField(verbose_name='last name')),
            ],
        ),
    ]
